### ISSUE TITLE
Are the numbers of each project sorted with their versions?

### ISSUE THREAD

**Issue by MinseokJGit** [Suresoft-GLaDOS/bugscpp#156]
For example, is cppcheck#30 a later version than cppcheck#1?

Does this hold for all the projects?

**Comment by Ye0nny** [comment]
Thank you for your question @MinseokJGit 

Unfortunately, a higher number does not necessarily indicate the latest version.
Currently, it is not considering the version order.

Please refer to the dates in the commit messages on the wiki.
https://github.com/Suresoft-GLaDOS/bugscpp/wiki

Thank you :)
